#!/bin/bash -e

MODULE=$(go list -m)
PKGS=$(go list ./...)
PKGS_DIRS=$(echo -n "$PKGS" | sed "s#$MODULE#.#g")

echo "Running tests..."
go test $PKGS -cover

echo "Running vet..."
go vet $PKGS

echo "Running gofmt..."
fmtRes=$(gofmt -l $PKGS_DIRS)
if [[ -n "${fmtRes}" ]]; then
	echo -e "gofmt checking failed:\n${fmtRes}"
	exit 2
fi

echo "Running golint..."
echo $PKGS | xargs -n 1 golint || true

echo "Success"
